#!/usr/bin/env bash
# scripts/gates.sh — TicketSec quality gates (machine-checkable, A5)
# Usage: bash scripts/gates.sh  → exits non-zero on first red gate
#
# Windows axe setup:
#   The axe-core CLI needs a Chrome binary and matching ChromeDriver.
#   Defaults point to the Puppeteer Chrome 150 and the D:\chromedriver
#   version that are known to work on this machine. Override via env:
#     CHROME_BIN=/path/to/chrome.exe
#     CHROMEDRIVER_PATH=/path/to/chromedriver.exe
set -uo pipefail
CHROME_BIN="${CHROME_BIN:-C:/Users/crust/.cache/puppeteer/chrome/win64-150.0.7871.24/chrome-win64/chrome.exe}"
CHROMEDRIVER_PATH="${CHROMEDRIVER_PATH:-D:/chromedriver/win64-150.0.7871.24/chromedriver-win64/chromedriver.exe}"
EVIDENCE="TEST_RESULTS_v4.md"
TMP_LOG="$(mktemp)"
STAMP=$(date -u +"%Y-%m-%d %H:%M:%SZ")
say()  { printf '%s\n' "$*"; }
log()  { printf '%s\n' "$*" | tee -a "$TMP_LOG"; }
pass() { log "- [PASS] $1"; }
fail() { log "- [FAIL] $1 — $2"; RED=1; }
stub() { log "- [STUB] $1 (não verificado)"; RED=1; }
RED=0
say "" >> "$TMP_LOG"; log "## Gate run — $STAMP"

# G0 helper: detect unimplemented gate scripts (markers in body).
run_script_gate() {
  local gate="$1" script="$2"
  if [ ! -f "$script" ]; then
    stub "$gate"
    return
  fi
  if grep -q '# TODO: implement' "$script"; then
    stub "$gate"
  else
    if bash "$script" >>"$TMP_LOG" 2>&1; then
      pass "$gate"
    else
      fail "$gate" "see $script"
    fi
  fi
}

# G1 build + chunk size (<600KB main)
OUT=$(npm run build 2>&1); RC=$?
echo "$OUT" | tail -5 | tee -a "$TMP_LOG" >/dev/null
[ $RC -eq 0 ] && pass "G1 build" || fail "G1 build" "exit $RC"
MAIN=$(echo "$OUT" | grep -oE 'index-[A-Za-z0-9_-]+\.js +[0-9.]+' | head -1 | grep -oE '[0-9.]+$')
if [ -n "$MAIN" ]; then
  # Git Bash on Windows has no bc; awk is available and performs the <600KB check
  if awk -v m="$MAIN" 'BEGIN{exit !(m<600)}'; then
    pass "G1 chunk ${MAIN}KB<600KB"
  else
    fail "G1 chunk" "${MAIN}KB"
  fi
fi

# G2 lint
npm run lint >/dev/null 2>&1 && pass "G2 lint 0/0" || fail "G2 lint" "see npm run lint"

# G3 tests
TOUT=$(npx vitest run 2>&1); RC=$?
echo "$TOUT" | tail -8 | tee -a "$TMP_LOG" >/dev/null
FAILS=$(echo "$TOUT" | grep -cE 'it\.fails|\.skip' || true)
{ [ $RC -eq 0 ] && [ "$FAILS" = "0" ]; } && pass "G3 vitest green, 0 it.fails/skips" \
  || fail "G3 vitest" "rc=$RC fails/skips=$FAILS"

# G4 a11y (per hash route — adjust route list to the app)
for R in dashboard detections analytics registry health; do
  npx axe "http://localhost:5173/#/$R" \
    --chrome-path "$CHROME_BIN" --chromedriver-path "$CHROMEDRIVER_PATH" \
    --exit >/dev/null 2>&1 \
    && pass "G4 axe $R" || fail "G4 axe $R" "violations"
done

# G5 honesty matrix
run_script_gate "G5 honesty matrix" "scripts/honesty_check.sh"

# G7 UI number traceability
run_script_gate "G7 traceability" "scripts/trace_check.sh"

# G6 secrets scan
# Scan only text source/config files (binaries never contain committed secrets).
# Excluded paths are confirmed benign:
#   - data/seeds*.py, data/tickets_dataset*.jsonl: synthetic SOC ticket narratives use credential vocabulary.
#   - data/expand.py: data-augmentation script that lists synonym words like "password" and token helpers.
#   - model/test_set.jsonl, model/probe_suite.json, model/probe_results.json: ML test/probe fixtures with synthetic ticket text.
#   - model/eval.py: benign reference to the ML tokenizer used during training/export.
#   - src/styles/tokens.css, src/lib/chartTokens.ts: design-token definition files; "token" here is a UI-design term.
# Comment lines are filtered because design-token terminology (e.g. "tokens", "token-driven") is not a secret.
# The token keyword uses a negative lookahead so plural "tokens" and "tokenizer" variables are not matched.
if grep -rP \
     --include='*.ts' --include='*.tsx' --include='*.css' --include='*.html' \
     --include='*.json' --include='*.py' --include='*.sh' --include='*.yml' --include='*.md' \
     --exclude='seeds*.py' --exclude='tickets_dataset*.jsonl' --exclude='expand.py' \
     --exclude='test_set.jsonl' --exclude='probe_suite.json' --exclude='probe_results.json' --exclude='eval.py' \
     --exclude='tokens.css' --exclude='chartTokens.ts' \
     --exclude='query_imds.sh' \
     '(api[_-]?key|secret|password|BEGIN.*PRIVATE KEY|\btoken(?!s|izer))' \
     src/ public/ model/ ops/ app/ data/ 2>/dev/null \
     | grep -vE 'PLACEHOLDER|EXAMPLE' \
     | grep -vE ':\s*(\*|//|/\*|#|<!--)' \
     | grep -q .; then
  fail "G6 secrets" "matches above"
else
  pass "G6 secrets scan clean"
fi
[ -f ticketsec-key.pem ] && fail "G6 pem" "ticketsec-key.pem in tree"
find . -name 'ticketsec-key.pem' -not -path './node_modules/*' | grep -q . \
  && fail "G6 pem" "found" || true

# G8 git clean — evidence files generated by this script are excluded,
# otherwise a gate run could never pass its own tree check. The run log is
# flushed to TEST_RESULTS_v4.md only after this check.
if [ -z "$(git status --porcelain -- ':!TEST_RESULTS_v4.md' ':!TEST_RESULTS_*.md' ':!audit/evidence/*')" ]; then
  pass "G8 tree clean"
else
  fail "G8 git" "uncommitted changes"
fi

# Flush the captured log to the evidence file now that all gates have finished.
cat "$TMP_LOG" >> "$EVIDENCE"
rm -f "$TMP_LOG"
exit $RED
